### ISSUE TITLE
URGENT: GEOCODE API DOESN'T ACCEPT FOREIGN IPS

### ISSUE THREAD

**Issue by whizzer0** [whizzer0/Im-Bored#2]
The Google Maps geocode API is returning an error that seems to suggest that it's only accepting the Neon Tribe IP address:
`{u'status': u'REQUEST_DENIED', u'error_message': u'This IP, site or mobile application is not authorized to use this API key. Request received from IP address 92.6.222.206, with empty referer', u'results': []}`

This bug is happening for me outside of Neon Tribe and is also the cause of the crash on the Python Anywhere host. I have no control over the API but this needs to be fixed now!

**Comment by chrisheath** [comment]
Yep I know what's going on the I will fix.
